### ISSUE TITLE
jboss-interceptor-api dependency not resolved

### ISSUE THREAD

**Issue by joan38** [sbt/sbt-assembly#236]
Hi guys,

Doesn't anyone else hit this issue?:
```
> sbt updateSbtClassifiers
[info] Loading project definition from /Users/joangoyeau/Code/test/project
[info] Updating {file:/Users/joangoyeau/Code/test/project/}test-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to test (in build file:/Users/joangoyeau/Code/test/)
[info] Resolving org.jboss.interceptor#jboss-interceptor-api;1.1 ...
[warn] problem while downloading module descriptor: https://repo1.maven.org/maven2/org/jboss/interceptor/jboss-interceptor-api/1.1/jboss-interceptor-api-1.1.pom: invalid sha1: expected=453b712ff6cda3a3f10f46a9ab9b9a42fc9bc021 computed=56da14e5a3e7e5656fe2ed1942d9fc0c1f3b054b (31ms)
[warn] 	module not found: org.jboss.interceptor#jboss-interceptor-api;1.1
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.jboss.interceptor/jboss-interceptor-api/1.1/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.jboss.interceptor/jboss-interceptor-api/1.1/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /Users/joangoyeau/.ivy2/local/org.jboss.interceptor/jboss-interceptor-api/1.1/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/jboss/interceptor/jboss-interceptor-api/1.1/jboss-interceptor-api-1.1.pom
[info] Resolving org.codehaus.plexus#plexus-classworlds;2.5.2 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.jboss.interceptor#jboss-interceptor-api;1.1: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
sbt.ResolveException: unresolved dependency: org.jboss.interceptor#jboss-interceptor-api;1.1: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:128)
	at sbt.IvySbt.withIvy(Ivy.scala:125)
	at sbt.IvySbt$Module.withModule(Ivy.scala:156)
	at sbt.IvyActions$.updateEither(IvyActions.scala:168)
	at sbt.IvyActions$.transitiveScratch(IvyActions.scala:228)
	at sbt.Classpaths$$anonfun$sbtClassifiersTasks$9$$anonfun$apply$74.apply(Defaults.scala:1375)
	at sbt.Classpaths$$anonfun$sbtClassifiersTasks$9$$anonfun$apply$74.apply(Defaults.scala:1373)
	at sbt.Classpaths$$anon$2.call(Defaults.scala:1403)
	at sbt.Classpaths$$anon$2.call(Defaults.scala:1400)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.Classpaths$.withExcludes(Defaults.scala:1400)
	at sbt.Classpaths$$anonfun$sbtClassifiersTasks$9.apply(Defaults.scala:1373)
	at sbt.Classpaths$$anonfun$sbtClassifiersTasks$9.apply(Defaults.scala:1364)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:updateSbtClassifiers) sbt.ResolveException: unresolved dependency: org.jboss.interceptor#jboss-interceptor-api;1.1: not found
[error] Total time: 7 s, completed 10-Feb-2017 12:30:34
```

I tried in an empty project with only this plugin in `plugins.sbt`.

**Comment by joan38** [comment]
I think I solved it by adding that to the begging of `plugins.sbt`
```
resolvers += "JBoss" at "https://repository.jboss.org"
```
This looks like a workaround tho.

**Comment by ltenny** [comment]
Yup...same problem here.  Adding the jboss repo worked for me as well.

**Comment by eed3si9n** [comment]
How does this relate to sbt-assembly?

**Comment by joan38** [comment]
@eed3si9n This is 100% related to sbt-assembly.
You can set an empty project and with just sbt-assembly in there and you will see that JBoss is not resolved.

Can we reopen this prematuredly closed issue?

**Comment by eed3si9n** [comment]
@joan38 Are you saying that sbt-assembly introduces dependency to org.jboss.interceptor:jboss-interceptor-api:1.1? As far as I know sbt-assembly has not direct or transitive dependency to it.

**Comment by joan38** [comment]
Yes that's what's happening.
I think it's not a direct transitive but in lower levels

**Comment by eed3si9n** [comment]
Do you have any global plugins?
 
Here's the full external dependency classpath from sbt-assembly, most coming from sbt itself.

```
[info] * Attributed(/org.scalactic/scalactic_2.10/bundles/scalactic_2.10-3.0.1.jar)
[info] * Attributed(/scala-2.10.6/lib/scala-library.jar)
[info] * Attributed(/scala-2.10.6/lib/scala-reflect.jar)
[info] * Attributed(/org.pantsbuild/jarjar/jars/jarjar-1.6.3.jar)
[info] * Attributed(/org.apache.ant/ant/jars/ant-1.9.6.jar)
[info] * Attributed(/org.apache.ant/ant-launcher/jars/ant-launcher-1.9.6.jar)
[info] * Attributed(/org.apache.maven/maven-plugin-api/jars/maven-plugin-api-3.3.3.jar)
[info] * Attributed(/org.apache.maven/maven-model/jars/maven-model-3.3.3.jar)
[info] * Attributed(/org.codehaus.plexus/plexus-utils/jars/plexus-utils-3.0.20.jar)
[info] * Attributed(/org.apache.maven/maven-artifact/jars/maven-artifact-3.3.3.jar)
[info] * Attributed(/org.eclipse.sisu/org.eclipse.sisu.plexus/eclipse-plugins/org.eclipse.sisu.plexus-0.3.0.jar)
[info] * Attributed(/javax.enterprise/cdi-api/jars/cdi-api-1.0.jar)
[info] * Attributed(/javax.annotation/jsr250-api/jars/jsr250-api-1.0.jar)
[info] * Attributed(/javax.inject/javax.inject/jars/javax.inject-1.jar)
[info] * Attributed(/org.eclipse.sisu/org.eclipse.sisu.inject/eclipse-plugins/org.eclipse.sisu.inject-0.3.0.jar)
[info] * Attributed(/org.codehaus.plexus/plexus-component-annotations/jars/plexus-component-annotations-1.5.5.jar)
[info] * Attributed(/org.codehaus.plexus/plexus-classworlds/bundles/plexus-classworlds-2.5.2.jar)
[info] * Attributed(/org.ow2.asm/asm/jars/asm-5.2.jar)
[info] * Attributed(/org.ow2.asm/asm-commons/jars/asm-commons-5.2.jar)
[info] * Attributed(/org.ow2.asm/asm-tree/jars/asm-tree-5.2.jar)
[info] * Attributed(/org.scala-sbt/sbt/jars/sbt-0.13.13.jar)
[info] * Attributed(/org.scala-sbt/main/jars/main-0.13.13.jar)
[info] * Attributed(/org.scala-sbt/actions/jars/actions-0.13.13.jar)
[info] * Attributed(/org.scala-sbt/classpath/jars/classpath-0.13.13.jar)
[info] * Attributed(/Users/eugene/.sbt/boot/scala-2.10.6/lib/scala-compiler.jar)
[info] * Attributed(/org.scala-sbt/interface/jars/interface-0.13.13.jar)
[info] * Attributed(/org.scala-sbt/io/jars/io-0.13.13.jar)
[info] * Attributed(/org.scala-sbt/control/jars/control-0.13.13.jar)
[info] * Attributed(/org.scala-sbt/launcher-interface/jars/launcher-interface-1.0.0-M1.jar)
[info] * Attributed(/org.scala-sbt/completion/jars/completion-0.13.13.jar)
[info] * Attributed(/org.scala-sbt/collections/jars/collections-0.13.13.jar)
[info] * Attributed(/jline/jline/jars/jline-2.13.jar)
[info] * Attributed(/org.fusesource.jansi/jansi/jars/jansi-1.11.jar)
[info] * Attributed(/org.scala-sbt/api/jars/api-0.13.13.jar)
[info] * Attributed(/org.scala-sbt/classfile/jars/classfile-0.13.13.jar)
[info] * Attributed(/org.scala-sbt/logging/jars/logging-0.13.13.jar)
[info] * Attributed(/org.scala-sbt/process/jars/process-0.13.13.jar)
[info] * Attributed(/org.scala-sbt/compiler-integration/jars/compiler-integration-0.13.13.jar)
[info] * Attributed(/org.scala-sbt/incremental-compiler/jars/incremental-compiler-0.13.13.jar)
[info] * Attributed(/org.scala-sbt/relation/jars/relation-0.13.13.jar)
[info] * Attributed(/org.scala-sbt/compile/jars/compile-0.13.13.jar)
[info] * Attributed(/org.scala-sbt/persist/jars/persist-0.13.13.jar)
[info] * Attributed(/org.scala-tools.sbinary/sbinary_2.10/jars/sbinary_2.10-0.4.2.jar)
[info] * Attributed(/org.scala-sbt/compiler-ivy-integration/jars/compiler-ivy-integration-0.13.13.jar)
[info] * Attributed(/org.scala-sbt/ivy/jars/ivy-0.13.13.jar)
[info] * Attributed(/org.scala-sbt/cross/jars/cross-0.13.13.jar)
[info] * Attributed(/org.scala-sbt.ivy/ivy/jars/ivy-2.3.0-sbt-2cf13e211b2cb31f0d3b317289dca70eca3362f6.jar)
[info] * Attributed(/com.jcraft/jsch/jars/jsch-0.1.50.jar)
[info] * Attributed(/org.scala-sbt/serialization_2.10/jars/serialization_2.10-0.1.2.jar)
[info] * Attributed(/org.scala-lang.modules/scala-pickling_2.10/jars/scala-pickling_2.10-0.10.1.jar)
[info] * Attributed(/org.scalamacros/quasiquotes_2.10/jars/quasiquotes_2.10-2.0.1.jar)
[info] * Attributed(/org.json4s/json4s-core_2.10/jars/json4s-core_2.10-3.2.10.jar)
[info] * Attributed(/org.json4s/json4s-ast_2.10/jars/json4s-ast_2.10-3.2.10.jar)
[info] * Attributed(/com.thoughtworks.paranamer/paranamer/jars/paranamer-2.6.jar)
[info] * Attributed(/org.spire-math/jawn-parser_2.10/jars/jawn-parser_2.10-0.6.0.jar)
[info] * Attributed(/org.spire-math/json4s-support_2.10/jars/json4s-support_2.10-0.6.0.jar)
[info] * Attributed(/org.scala-sbt/run/jars/run-0.13.13.jar)
[info] * Attributed(/org.scala-sbt/task-system/jars/task-system-0.13.13.jar)
[info] * Attributed(/org.scala-sbt/tasks/jars/tasks-0.13.13.jar)
[info] * Attributed(/org.scala-sbt/tracking/jars/tracking-0.13.13.jar)
[info] * Attributed(/org.scala-sbt/cache/jars/cache-0.13.13.jar)
[info] * Attributed(/org.scala-sbt/testing/jars/testing-0.13.13.jar)
[info] * Attributed(/org.scala-sbt/test-agent/jars/test-agent-0.13.13.jar)
[info] * Attributed(/org.scala-sbt/test-interface/jars/test-interface-1.0.jar)
[info] * Attributed(/org.scala-sbt/main-settings/jars/main-settings-0.13.13.jar)
[info] * Attributed(/org.scala-sbt/apply-macro/jars/apply-macro-0.13.13.jar)
[info] * Attributed(/org.scala-sbt/command/jars/command-0.13.13.jar)
[info] * Attributed(/org.scala-sbt/template-resolver/jars/template-resolver-0.1.jar)
[info] * Attributed(/org.scala-sbt/logic/jars/logic-0.13.13.jar)
[info] * Attributed(/org.scala-sbt/compiler-interface/jars/compiler-interface-0.13.13.jar)
```

**Comment by joan38** [comment]
No I don't have any global plugins.
This issue appeared quiet recently. I suspect some repo changed.
This issue appeared first on our CI that is rebuilding a docker image with the SBT cache every WE.

**Comment by joan38** [comment]
Steps to reproduce:
```
mkdir test
cd test
mkdir project
echo "addSbtPlugin(\"com.eed3si9n\" % \"sbt-assembly\" % \"0.14.4\")" > project/plugins.sbt
rm -rf ~/.ivy2
sbt updateSbtClassifiers
```

**Comment by eed3si9n** [comment]
ok. I was able to reproduce the error.

```
$ sbt -Dsbt.ivy.home=/tmp/test/ivy2/ -Dsbt.global.base=/tmp/test/global debug updateSbtClassifiers
```

I'm not sure what's causing it to resolve. Perhaps I can exclude dependency to maven-plugin-api if that's getting pulled in via Jar Jar Links.

**Comment by fommil** [comment]
this is a particularly nasty one because the sha `453b712ff6cda3a3f10f46a9ab9b9a42fc9bc021` on maven central doesn't match the pom file, yay!

**Comment by fommil** [comment]
workaround is to install with

```
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.4" exclude("org.apache.maven", "maven-plugin-api"))
```

**Comment by fommil** [comment]
(this wiped me out for a full day at scalasphere because the sha mismatch took down our CI, so hopefully this helps somebody nail it down)

**Comment by brentsony** [comment]
Thank you, Fommil - yes, that fixes the IDEA bug.  (SBT always compiled the project fine -- it was just a recent IDEA import bug).

**Comment by joan38** [comment]
@brentsony this is unrelated to Idea, you can reproduce the issue by doing `sbt updateSbtClassifiers` as I showed in my first message.

**Comment by brentsony** [comment]
@joan38 Yes, thank you for noting that there is a way to break SBT outside of IDEA. However, IDEA is broken by the bug and does not offer a workaround. All the usual workarounds have no effect. That is, ReBuild All, Invalidate Caches and Restart, Deleting the target dir and building, ... IDEA is so broken that it cannot even display syntax highlighting in build.sbt and gives completely misleading compilation error messages in perfectly valid Scala source files. All the while, "sbt clean compile" works great from the command line.

**Comment by joan38** [comment]
@brentsony You see this issue in idea because the command ran by Idea in SBT is:
```
;reload; */*:dumpStructureTo /private/var/folders/4_/0czwjnyn1tb8slhkcvcl3tjc0000gp/T/sbt-structure.xml download resolveClassifiers resolveSbtClassifiers
```
You can see that `resolveSbtClassifiers` is in this list of tasks.

**Comment by sihil** [comment]
Also hit this. I'm using coursier and get this error:
```
[trace] Stack trace suppressed: run last *:coursierSbtClassifiersResolution for the full output.
[error] (*:coursierSbtClassifiersResolution) coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
[error]   org.jboss.interceptor:jboss-interceptor-api:1.1:
[error]     not found:
[error]       https://repo.typesafe.com/typesafe/ivy-releases/org.jboss.interceptor/jboss-interceptor-api/1.1/ivys/ivy.xml
[error]       https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.jboss.interceptor/jboss-interceptor-api/1.1/ivys/ivy.xml
[error]       /Users/shildrew/.ivy2/local/org.jboss.interceptor/jboss-interceptor-api/1.1/ivys/ivy.xml
[error]       https://repo.typesafe.com/typesafe/releases/org/jboss/interceptor/jboss-interceptor-api/1.1/jboss-interceptor-api-1.1.pom
[error]     wrong checksum: /Users/shildrew/.coursier/cache/v1/https/repo1.maven.org/maven2/org/jboss/interceptor/jboss-interceptor-api/1.1/jboss-interceptor-api-1.1.pom
[error] Total time: 3 s, completed 20-Apr-2017 15:14:12
```

So at least the root cause of an invalid checksum is clear when coursier is enabled.

**Comment by caoilte** [comment]
Some discussion of this issue on Stackoverflow

http://stackoverflow.com/questions/41966066/jboss-interceptor-api-1-1-not-found-when-added-as-sbt-dependency

**Comment by graingert** [comment]
If anyone tried opening the issue on the correct project maybe it wouldn't have taken 5 months to fix: https://issues.sonatype.org/plugins/servlet/mobile#issue/MVNCENTRAL-2461

**Comment by graingert** [comment]
@eed3si9n fyi it's fixed now: you can close the issue.

**Comment by vn971** [comment]
@graingert I don't see it being fixed. It's still broken for me. Maybe you have the correct dependency in your ~/.ivy2 now, or a custom dependency resolver, @graingert ?

@eed3si9n can sbt-assembly explicitly remove jboss-interceptor-api from its dependencies? After all, everything works when using `addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.4" exclude("org.apache.maven", "maven-plugin-api"))` (as suggested by fommil).

**Comment by graingert** [comment]
@vn971 no it's definitely fixed. Read the discussion on https://issues.sonatype.org/browse/MVNCENTRAL-2461

**Comment by vn971** [comment]
@graingert indeed, the issue is fixed now. One has to clean up jboss-related files from ivy cache (`~/.ivy2` or `~/.coursier`) in order for things to work. Thank you.

@eed3si9n is there actually any reason to keep sbt-assembly dependent on jboss-interceptor-api at all? Is it really used? Because everything works fine when using `addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.4" exclude("org.apache.maven", "maven-plugin-api"))` (as suggested by @fommil).

**Comment by alexarchambault** [comment]
With coursier, this should be ok since 1.0.0. sbt-coursier was generating an update report for plugins which was lacking some exclusions, which later made `updateSbtClassifiers` try to pull too many things, including some jboss stuff with wrong checksums (which should have been excluded).

This is specific to coursier, so I don't know about the cases where this was happening without it…

**Comment by graingert** [comment]
@eed3si9n fyi it's fixed now: you can close the issue.

**Comment by eed3si9n** [comment]
@graingert Thanks!
